<a href="https://colab.research.google.com/github/maheshpandao/Mahesh/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Single diamensional array

In [ ]:
import numpy as np
a=np.array([1,00,3,2,3])
a

array([1, 0, 3, 2, 3])

Multi diamensional array

In [ ]:
import numpy as np
a=np.array(([1,00,3,2,3]),([1,2,3,6,5]),([2,3,5,5,6]))
a

TypeError: ignored

Generating array

In [ ]:
c= np.arange(10)  #range of values in array
d= np.linspace(1,5,6)  # set of values by interval [start,end,no.of caluesEquation]
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.8 2.6 3.4 4.2 5. ]


Array properties


In [ ]:
a = np.array([7,7,9,8])
b = np.array([(5,6,9,6),(6,9,8,5)])
print(a.ndim)#dimension of array
print(b.ndim)#dimension of array
print(a.itemsize)#Byte size of each element
print(b.itemsize)#byte size of each element
print(a.dtype)#datatype of array
print(b.dtype)#datatype of array
print(a.size*a.itemsize)#memory occupied - space occupied by one element * length of array
print(b.size*b.itemsize)# memory occupied - space occupied by one element * length of array
print(a.size)#number of elements in array
print(b.size)
print(b.shape) #shape of array(rows and coloumn)          

1
2
8
8
int64
int64
32
64
4
8
(2, 4)


array reshaping

In [ ]:
b = np.array([(5,6,9,6),(6,9,8,5)])
print(b)
b=b.reshape(4,2)
print(b)

[[5 6 9 6]
 [6 9 8 5]]
[[5 6]
 [9 6]
 [6 9]
 [8 5]]


Array slicing

In [ ]:
b = np.array([(1,3,6,5),(3,6,8,9)])
print((b[0,2])) # slicing element from certain row and certain coloumn b[rowIndex, ColoumnIndex]

print(b[0:,2])# Slicing element from all rows and certain coloumn

6
[6 8]


Array value operation

In [ ]:
e = np.array([5,6,5,2,3,6,2])
print(e.min())
print(e.max())
print(e.sum())

2
6
29


Arithmetic operation

In [ ]:
a = np.array([7,7,9,8])
b = np.array([5,6,9,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[12 13 18 14]
[2 1 0 2]
[35 42 81 48]
[1.4        1.16666667 1.         1.33333333]


I

Important operations on Array

In [ ]:
a = np.array([7,9,9,2])
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b.sum(axis=0)) # Each element of 1st dim array with same index with another dim element
print(b.sum(axis=1)) #Sum of all elements is 1dia and sum of all element is 2nd dim

[23 20 18  8]
[27 42]


In [ ]:
print(np.sqrt(a))#squareroot of array element

[2.64575131 3.         3.         1.41421356]


In [ ]:
print(np.std(a)) #standard deviation

2.8613807855648994


In [ ]:
print(np.exp(a)) #Exponetial of array

[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]


In [ ]:
print(np.log(a)) #Natural log -In

[1.94591015 2.19722458 2.19722458 0.69314718]


In [ ]:
print(np.log10(a)) #Logbase 10

[0.84509804 0.95424251 0.95424251 0.30103   ]


Vertical stack and horizontal stack

In [ ]:
b = np.array([(7,9,9,2),(16,11,9,6)])
f = np.array([(1,2,3,4),(5,6,7,8)])
print(np.vstack((b,f))) # verticle stack

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [ ]:
print(np.hstack((b,f))) #horizontal stack

[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]


In [ ]:
print(b.ravel()) #Merging as single

[ 7  9  9  2 16 11  9  6]
